FROM ubuntu:latest
LABEL maintainer.name="Paul Schragger" \
    maintainer.email="paul.schragger@gmail.com" \
    version="0.0.1" \
    description="wakaama server - lwm2m protocol reference stack"

RUN apt-get update
RUN apt-get install -y cmake make

EXPOSE 5683

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./examples/bootstrap_server/requirements.txt /usr/src/app/

COPY . .

RUN cmake ./examples/bootstrap_server
RUN make
RUN pwd
RUN ls -al  bootstrapserver
ENTRYPOINT ["/usr/src/app/bootstrapserver"]


